Revert "Make libutils test compile on the host"
Fails mac build: "system/core/include/utils/Looper.h:25:10: fatal error: 'sys/epoll.h' file not found"

This reverts commit df7ef08d251a4deb77056a0c1d7afd68e77473e4.

Change-Id: Ib558b8f5a303b55ab32a399d338d8aac0fae32b2